version: '3'
services:
  jupyter-ds:
      build:
        context: .
        dockerfile: ./dockerfiles/dockerfile
      user: root
      environment:
        - GRANT_SUDO=yes
        - JUPYTER_ENABLE_LAB=yes
        - JUPYTER_TOKEN=qlrThf1!
      volumes:
        - /Users/jinhyounglee/Documents/workplace/docker/jupyter/data:/home/jovyan/data
      ports:
        - "8888:8888"
      container_name: "jupyter-ds"
      # entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/opt/app/data --allow-root'
