FROM jupyter/all-spark-notebook:latest
# Declare root as user
USER root
# Update Ubuntu
RUN sed -i 's/archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list && sed -i 's/security.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list
# Install Nanum for Korean Font
RUN apt-get update && apt-get -y upgrade && apt-get install -y fonts-nanum* && fc-cache -fv && rm -fr ~/.cache/matplotlib && pip install jupyter_nbextensions_configurator \
    && jupyter serverextension enable --py jupyterlab --sys-prefix && jupyter nbextensions_configurator enable --user && pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install --user && pip install plotly  \
    && pip install pymysql && pip install kaleido && conda install -c conda-forge python-kaleido && conda install -c conda-forge jupyterlab jupyterlab-git



# Expose Jupyter port & cmd
# EXPOSE 8888
# CMD jupyter lab --ip=* --port=8888 --no-browser --notebook-dir=/opt/app/data --allow-root
